# Generated by Django 4.0.2 on 2023-02-12 04:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flixter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='tags',
            field=models.ManyToManyField(to='flixter.Tag'),
        ),
        migrations.CreateModel(
            name='Upcoming',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150)),
                ('description', models.TextField(blank=True, null=True)),
                ('file', models.FileField(upload_to='movies/')),
                ('preview_image', models.ImageField(upload_to='preview_images/')),
                ('data_created', models.DateTimeField(auto_now_add=True)),
                ('categories', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flixter.category')),
                ('tags', models.ManyToManyField(to='flixter.Tag')),
            ],
        ),
        migrations.CreateModel(
            name='TopTen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150)),
                ('description', models.TextField(blank=True, null=True)),
                ('watch_count', models.IntegerField(default=0)),
                ('file', models.FileField(upload_to='movies/')),
                ('preview_image', models.ImageField(upload_to='preview_images/')),
                ('data_created', models.DateTimeField(auto_now_add=True)),
                ('categories', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flixter.category')),
                ('tags', models.ManyToManyField(to='flixter.Tag')),
            ],
        ),
    ]
