# Generated by Django 4.1.6 on 2023-02-21 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flixter', '0002_alter_movie_tags_upcoming_topten'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topten',
            old_name='watch_count',
            new_name='rating',
        ),
    ]
