# Generated by Django 4.1.6 on 2023-02-21 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flixter', '0003_rename_watch_count_topten_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topten',
            old_name='description',
            new_name='image',
        ),
        migrations.AddField(
            model_name='topten',
            name='emsId',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
