# Generated by Django 4.1.7 on 2023-02-22 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flixter', '0004_rename_description_topten_image_topten_emsid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topten',
            name='categories',
        ),
    ]
