# Generated by Django 4.1.7 on 2023-02-22 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flixter', '0006_rename_description_upcoming_emsid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='upcoming',
            name='categories',
        ),
    ]
