# Generated by Django 4.1.7 on 2023-02-22 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flixter', '0007_remove_upcoming_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='date',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='movie',
            name='image',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='rating',
            field=models.IntegerField(default=1),
        ),
    ]
