# Generated by Django 4.1.7 on 2023-02-22 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flixter', '0009_remove_movie_categories_movie_emsid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='upcoming',
            name='rating',
            field=models.IntegerField(default=0),
        ),
    ]
