# Generated by Django 4.1.7 on 2023-02-23 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flixter', '0010_upcoming_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='date',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
