# Generated by Django 4.1.7 on 2023-02-24 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flixter', '0011_alter_movie_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='emsId',
            new_name='movie_id',
        ),
        migrations.RenameField(
            model_name='topten',
            old_name='emsId',
            new_name='movie_id',
        ),
        migrations.RenameField(
            model_name='upcoming',
            old_name='emsId',
            new_name='movie_id',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='file',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='preview_image',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='watch_count',
        ),
        migrations.RemoveField(
            model_name='topten',
            name='file',
        ),
        migrations.RemoveField(
            model_name='topten',
            name='preview_image',
        ),
        migrations.RemoveField(
            model_name='topten',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='upcoming',
            name='preview_image',
        ),
        migrations.RemoveField(
            model_name='upcoming',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='upcoming',
            name='tags',
        ),
    ]
